print("JOMON SEBASTIAN")
print("21MCA025")
import cmath
a=float(input("enter the value of a"))
b=float(input("enter the value of b"))
c=float(input("enter the value of c"))
d=b*b-(4*a*c)
s=(-b-cmath.sqrt(d))/(2*a)
t=(-b+cmath.sqrt(d))/(2*a)
print("s",s)
print("t",t)